### ISSUE TITLE
Memory errors reported by `-fsanitize=address` instrumentation

### ISSUE THREAD

**Issue by MagaTailor** [ptitSeb/gl4es#21]
$  LD_PRELOAD=/usr/gcc7/lib/libasan.so.4 **foobillardplus**

```shell
==24249==ERROR: AddressSanitizer: global-buffer-overflow on address 0xb6994c58 at pc 0xb694e98c bp 0xbe88f61c sp 0xbe88f614
READ of size 4 at 0xb6994c58 thread T0
    #0 0xb694e98b in gl4es_glPolygonOffset ../src/gl/wrap/gles.c:1326

0xb6994c58 is located 40 bytes to the left of global variable '*.LC2' defined in '../src/gl/wrap/gles.c' (0xb6994c80) of size 17
  '*.LC2' is ascii string 'glTexParameterxv'
0xb6994c58 is located 0 bytes to the right of global variable 'StageExclusive' defined in '../src/gl/wrap/../list.h:32:12' (0xb6994c00) of size 88
SUMMARY: AddressSanitizer: global-buffer-overflow ../src/gl/wrap/gles.c:1326 in gl4es_glPolygonOffset
Shadow bytes around the buggy address:
  0x36d32930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x36d32940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x36d32950: 03 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x36d32960: 00 00 00 00 00 00 00 00 00 00 00 00 00 05 f9 f9
  0x36d32970: f9 f9 f9 f9 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9
=>0x36d32980: 00 00 00 00 00 00 00 00 00 00 00[f9]f9 f9 f9 f9
  0x36d32990: 00 00 01 f9 f9 f9 f9 f9 00 00 00 00 00 06 f9 f9
  0x36d329a0: f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x36d329b0: 00 05 f9 f9 f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9
  0x36d329c0: 00 00 00 00 00 06 f9 f9 f9 f9 f9 f9 00 00 01 f9
  0x36d329d0: f9 f9 f9 f9 00 00 00 00 00 06 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24249==ABORTING
````

$ LD_PRELOAD=/usr/gcc7/lib/libasan.so.4 **billard-gl**

```shell
==24446==ERROR: AddressSanitizer: global-buffer-overflow on address 0xb693fd38 at pc 0xb68740f4 bp 0xbe91fb14 sp 0xbe91fb0c
READ of size 4 at 0xb693fd38 thread T0
    #0 0xb68740f3 in gl4es_glMultMatrixf ../src/gl/matrix.c:185
    #1 0xb68740f3 in gl4es_glTranslatef ../src/gl/matrix.c:224
    #2 0x1cc0d  (/usr/games/billard-gl+0x1cc0d)
    #3 0x15263  (/usr/games/billard-gl+0x15263)
    #4 0x2404b  (/usr/games/billard-gl+0x2404b)

0xb693fd38 is located 40 bytes to the left of global variable '*.LC0' defined in '../src/gl/matrix.c' (0xb693fd60) of size 13
  '*.LC0' is ascii string 'glMatrixMode'
0xb693fd38 is located 0 bytes to the right of global variable 'StageExclusive' defined in '../src/gl/list.h:32:12' (0xb693fce0) of size 88
SUMMARY: AddressSanitizer: global-buffer-overflow ../src/gl/matrix.c:185 in gl4es_glMultMatrixf
Shadow bytes around the buggy address:
  0x36d27f50: f9 f9 f9 f9 05 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x36d27f60: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 00 05 f9 f9
  0x36d27f70: f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9 00 02 f9 f9
  0x36d27f80: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x36d27f90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x36d27fa0: 00 00 00 00 00 00 00[f9]f9 f9 f9 f9 00 05 f9 f9
  0x36d27fb0: f9 f9 f9 f9 00 00 00 00 00 02 f9 f9 f9 f9 f9 f9
  0x36d27fc0: 00 06 f9 f9 f9 f9 f9 f9 00 00 00 00 00 03 f9 f9
  0x36d27fd0: f9 f9 f9 f9 00 07 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x36d27fe0: 00 04 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x36d27ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24446==ABORTING
````

I wasn't able to trigger any more complaints from `libasan`,  great!

**Comment by ptitSeb** [comment]
Should be fixed now.

**Comment by MagaTailor** [comment]
Thanks, I've been unable to find any new serious errors in the stuff I've tested, apart from this "warning":

$ LD_PRELOAD=/usr/gcc7/lib/libasan.so.4 **armagetronad**

```shell
../src/gl/pixel.c:150:9: runtime error: load of misaligned address 0xad100801 for type 'GLushort *[16]', which requires 2 byte alignment
0xad100801: note: pointer points here
 00 80 1b  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
````

**Comment by ptitSeb** [comment]
I cannot avoid these kind of misaligned access without using copy-schemes that will slow down pixel conversion stuff. So I'll probably keep it like it is for now, unless that trigger some BusError at some point.

**Comment by MagaTailor** [comment]
Right, shall we close then?

**Comment by ptitSeb** [comment]
Yep :)
