### ISSUE TITLE
Minecraft Java (pojavlauncher)fabric settings not working properly(1.16.3)(sodium)

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#255]
Hi great developer (ptitseb)..its me again..i was wondering if this could be a gl4es rendering error or mobile drivers(also i have a rog phone 2)..

![Screenshot_20201203-092715956.jpg](https://user-images.githubusercontent.com/63176856/101018491-58498f80-354a-11eb-9a4e-90d685c03e26.jpg)

This setting is having that problem below (in game)

![Screenshot_20201203-092730377.jpg](https://user-images.githubusercontent.com/63176856/101018555-6f887d00-354a-11eb-99e1-c9f2ed14c4f4.jpg)

Also..that other is giving a crash..

![Screenshot_20201203-092707819.jpg](https://user-images.githubusercontent.com/63176856/101018596-8038f300-354a-11eb-8e44-48ef8f500575.jpg)

Hope there is a fix...blessed day

---- Minecraft Crash Report ----
// Why did you do that?

Time: 03-12-2020 12:23
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:0
	at net.minecraft.class_276.method_1239(class_276.java:180)
	at net.minecraft.class_276.method_1231(class_276.java:149)
	at net.minecraft.class_276.method_22596(class_276.java:65)
	at net.minecraft.class_276.method_1234(class_276.java:54)
	at net.minecraft.class_276.<init>(class_276.java:45)
	at net.minecraft.class_310.<init>(class_310.java:466)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_276.method_1239(class_276.java:180)
	at net.minecraft.class_276.method_1231(class_276.java:149)
	at net.minecraft.class_276.method_22596(class_276.java:65)
	at net.minecraft.class_276.method_1234(class_276.java:54)
	at net.minecraft.class_276.<init>(class_276.java:45)
	at net.minecraft.class_310.<init>(class_310.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 697247632 bytes (664 MB) / 1811939328 bytes (1728 MB) up to 1912602624 bytes (1824 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms512m -Xmx1800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 9x null

**Comment by pedrosouzabrasil** [comment]
Also..i want to say thanks for helping fix the bugs..in game..!

**Comment by ptitSeb** [comment]
The Fog Occlusion setting: Occlusion is not supported on gl4es. There are stub occlusion functions that do nothing. Occlusion needs hardware support, which only exist in an extension on GLES2, and gl4es doesn't use that extension anyway.
For now, Fog occlusion is NO GO.

No idea what the compact vertex format is using, but it may be some unsopported never used format that is not handled. The log is not helpfull, and I still have no time for this. Just don't use that.

There are many settings that work, just don't use the 2 that doesn't work (and will not bring any benefits anyway, has data would get converted to a supported format anyway).

**Comment by pedrosouzabrasil** [comment]
You are so smart!thanks
